stages:
  - ansible-lint
ansible-lint:
  stage: ansible-lint
  image: python:3-slim
  services:
    - docker:19.03-dind
  before_script:
  - pip install --upgrade ansible-lint yamllint
  - yamllint --version
  - ansible-lint --version
  script:
    - yamllint -c ./.yamllint ./tasks/*.yml
    - yamllint -c ./.yamllint *.yaml
    - ansible-lint ./tasks/*.yml
    - ansible-lint .
  tags:
    - docker
    - shared

